[package]
name = "hello-rust"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["rt-multi-thread"] }
tokio-stream = "0.1.11"
serde = { version = "1.0.148", features = ["derive"] }
serde_json = "1.0.89"
serde_dynamo = { version = "4.0.9", features = ["aws-sdk-dynamodb+0_21"] }
config = { version = "0.13.2", features = [] }
yup-oauth2 = "7.0.1"
aws-config = "0.51.0"
aws-sdk-dynamodb = "0.21.0"
thiserror = "1.0.37"
anyhow = "1.0.68"
