---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hello-rust-backend
  annotations:
    github.com/project-slug: SG60/hello-rust
spec:
  type: service
  lifecycle: dev
  owner: main
  system: notion-sync
  dependsOn:
    - resource:tasks-db
    - resource:oracle-k8s
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: notion-sync
spec:
  owner: main
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: tasks-db
  description: Stores data for notion gcal sync (DynamoDB)
spec:
  type: database
  owner: main
  system: notion-sync
---
